# Render Blueprint - Pabau-Mailchimp Sync System
# Deploys PostgreSQL database, web dashboard, and cron jobs for syncing

databases:
  - name: pabau-mailchimp-db
    databaseName: pabau_mailchimp
    user: pabau_user
    region: oregon
    plan: free  # Options: free (1GB, expires in 30 days), starter ($7/mo, 10GB, backups)
    ipAllowList: []
    postgresMajorVersion: "15"

services:
  # WEB DASHBOARD: View sync logs and statistics
  - type: web
    name: pabau-mailchimp-dashboard
    runtime: python
    region: oregon
    plan: free
    healthCheckPath: /health
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn dashboard:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pabau-mailchimp-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
  # UNIFIED SYNC: Runs all 3 sync operations sequentially (every 3 hours)
  # Order: Pabau→DB → Mailchimp Unsubscribes→DB → DB→Mailchimp
  - type: cron
    name: unified-sync
    runtime: python
    region: oregon
    schedule: "0 */3 * * *"  # Every 3 hours (at :00)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scripts/sync/sync_all.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pabau-mailchimp-db
          property: connectionString
      - key: PABAU_API_KEY
        sync: false
      - key: PABAU_API_URL
        sync: false
      - key: PABAU_COMPANY_ID
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_API_URL
        sync: false
      - key: MAILCHIMP_LIST_ID
        sync: false
