# Render Blueprint - Pabau-Mailchimp Sync System
# Deploys PostgreSQL database, web dashboard, and cron jobs for syncing

databases:
  - name: pabau-mailchimp-db
    databaseName: pabau_mailchimp
    user: pabau_user
    region: oregon
    plan: free  # Options: free (1GB, expires in 30 days), starter ($7/mo, 10GB, backups)
    ipAllowList: []
    postgresMajorVersion: "15"

services:
  # WEB DASHBOARD + BACKGROUND SCHEDULER
  # Dashboard shows sync logs and statistics
  # Background scheduler runs sync every 3 hours
  - type: web
    name: pabau-mailchimp-dashboard
    runtime: python
    region: oregon
    plan: free
    healthCheckPath: /health
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pabau-mailchimp-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PABAU_API_KEY
        sync: false
      - key: PABAU_API_URL
        sync: false
      - key: PABAU_COMPANY_ID
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false
      - key: MAILCHIMP_API_URL
        sync: false
      - key: MAILCHIMP_LIST_ID
        sync: false
      - key: RUN_INITIAL_SYNC
        value: "false"  # Set to "true" to run sync immediately on startup
